name: Hoo-Ray
version: 0.1.0.0
github: "denx20/Hoo-Ray"
license: BSD3
author: "Yuxi Long, Shiyou Wu, Yingjie Xu"
maintainer: "yuxi.long@duke.edu, shiyou.wu@duke.edu, yingjie.xu@duke.edu"
copyright: "2023 Yuxi Long, Shiyou Wu, and Yingjie Xu"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/denx20/Hoo-Ray/blob/main/README.md>

dependencies:
  - base
  - haskell-src-exts
  - mtl
  - random
  - parallel
  - optparse-applicative
  - text
  - distributed-process
  - distributed-process-async
  - distributed-process-simplelocalnet
  - binary
  - unordered-containers
  - hashable
  - time

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  # Core of this package
  queue:
    main: Queue.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Hoo-Ray
  build_graph:
    main: build_graph.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Hoo-Ray

  # Test generator
  matmul_test_gen:
    main: MatMulTestGen.hs
    source-dirs: test-gen
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

  # Testing tasks single-threaded
  matmul_ss_test:
    main: matmul_ss_test.hs
    source-dirs: test
    dependencies:
      - Hoo-Ray
  matmul_ms_test:
    main: matmul_ms_test.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Hoo-Ray
  mlp_example:
    main: mlp_example.hs
    source-dirs: test
    dependencies:
      - Hoo-Ray
  transformer_example:
    main: transformer_example.hs
    source-dirs: test
    dependencies:
      - Hoo-Ray
