name: HooRay
version: 0.1.0.0
github: "githubuser/HooRay"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2023 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/HooRay#readme>

dependencies:
  - base >= 4.7 && < 5
  - syb
  - mtl
  - haskell-src-exts
  - text
  - random
  - optparse-applicative
  - async
  - distributed-process
  - binary
  - unordered-containers
  - hashable
  - time
  - distributed-process-simplelocalnet
  - distributed-process-async

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  queue:
    main: Queue.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HooRay
  matmul_test_gen:
    main: MatMulTestGen.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HooRay
